//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SamplePanoBGs
{

    // To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SamplePanoBGs { }
#else

	public class SamplePanoBGs : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SamplePanoBGs()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/weave;component/SampleData/SamplePanoBGs/SamplePanoBGs.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Backgrounds _Backgrounds = new Backgrounds();

		public Backgrounds Backgrounds
		{
			get
			{
				return this._Backgrounds;
			}
		}
	}

	public class BackgroundsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _SourceUrl = string.Empty;

		public string SourceUrl
		{
			get
			{
				return this._SourceUrl;
			}

			set
			{
				if (this._SourceUrl != value)
				{
					this._SourceUrl = value;
					this.OnPropertyChanged("SourceUrl");
				}
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}
	}

	public class Backgrounds : System.Collections.ObjectModel.ObservableCollection<BackgroundsItem>
	{ 
	}
#endif
}
