//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleHomePageTasks
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleHomePageTasks { }
#else

	public class SampleHomePageTasks : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleHomePageTasks()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/weave;component/SampleData/SampleHomePageTasks/SampleHomePageTasks.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private HomePageTasks _HomePageTasks = new HomePageTasks();

		public HomePageTasks HomePageTasks
		{
			get
			{
				return this._HomePageTasks;
			}
		}
	}

	public class HomePageTasksItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Icon = string.Empty;

		public string Icon
		{
			get
			{
				return this._Icon;
			}

			set
			{
				if (this._Icon != value)
				{
					this._Icon = value;
					this.OnPropertyChanged("Icon");
				}
			}
		}

		private string _Caption = string.Empty;

		public string Caption
		{
			get
			{
				return this._Caption;
			}

			set
			{
				if (this._Caption != value)
				{
					this._Caption = value;
					this.OnPropertyChanged("Caption");
				}
			}
		}
	}

	public class HomePageTasks : System.Collections.ObjectModel.ObservableCollection<HomePageTasksItem>
	{ 
	}
#endif
}
