//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleBrowseFeedsByCategoryViewModel
{

    // To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleBrowseFeedsByCategoryViewModel { }
#else

	public class SampleBrowseFeedsByCategoryViewModel : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleBrowseFeedsByCategoryViewModel()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/weave;component/SampleData/SampleBrowseFeedsByCategoryViewModel/SampleBrowseFeedsByCategoryViewModel.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Feeds _Feeds = new Feeds();

		public Feeds Feeds
		{
			get
			{
				return this._Feeds;
			}
		}

		private string _Category = string.Empty;

		public string Category
		{
			get
			{
				return this._Category;
			}

			set
			{
				if (this._Category != value)
				{
					this._Category = value;
					this.OnPropertyChanged("Category");
				}
			}
		}
	}

	public class FeedsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private bool _IsEnabled = false;

		public bool IsEnabled
		{
			get
			{
				return this._IsEnabled;
			}

			set
			{
				if (this._IsEnabled != value)
				{
					this._IsEnabled = value;
					this.OnPropertyChanged("IsEnabled");
				}
			}
		}
	}

	public class Feeds : System.Collections.ObjectModel.ObservableCollection<FeedsItem>
	{ 
	}
#endif
}
